[[source]]
  name = "1982"
  artist = "Haircuts for Men"
  url = "https://www.youtube.com/watch?v=HSp0E0kCzVc"
  path = "vapor/chirpy/"
  timestamps = ["00:00","04:18","08:47","13:15","17:25"]
  namestamps = ["Henry's Lunch Money","Car Key Jingle","Weakling Heart","Acceptance","Midnight Luxxury"]
